### ISSUE TITLE
Ground Truth/Entity Graph

### ISSUE THREAD

**Issue by dipplestix** [siteadmin/Patient-Matching#1]
Is there a file with the ground truth you can make available so the performance of newly developed matching algorithms can be tested?

**Comment by doh-FXX0303** [comment]
Any update to developing a 'ground truth' or answer key?

**Comment by carmenjsmiley** [comment]
Hello @dipplestix and @doh-FXX0303. Thanks for your inquiry. At this time, ONC has no plan to develop an answer key for developing and testing matching algorithms.
